In [1]:
import pickle
import json
import pandas
import scipy

In [2]:
descdict = dict()

with open('obj/descdict.pkl', 'rb') as handle:
    descdict = pickle.load(handle)

keys = list(descdict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [3]:
onehotdf = pandas.DataFrame()

with open('obj/onehotdf.pkl', 'rb') as handle:
    onehotdf = pickle.load(handle)

keys = list(onehotdf.keys())
print(keys)

['swagger', 'info', 'host', 'basePath', 'schemes', 'consumes', 'produces', 'paths', 'definitions', 'parameters', 'responses', 'securityDefinitions', 'security', 'tags', 'externalDocs', 'implemented fields', 'missing fields']


In [4]:
onehotdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [5]:
lemmadict = dict()

with open('obj/lemmadict.pkl', 'rb') as handle:
    lemmadict = pickle.load(handle)

keys = list(lemmadict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [6]:
onehotdict = dict()

with open('obj/onehotdict.pkl', 'rb') as handle:
    onehotdict = pickle.load(handle)

keys = list(onehotdict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [7]:
onehotdict[keys[0]]

[1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]

In [8]:
import sys
!{sys.executable} -m pip install kmodes



You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [9]:
import numpy as np
from kmodes.kmodes import KModes


In [10]:
onehotdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [35]:
spec_key_complete = []
spec_key_complete.append('swagger')
spec_key_complete.append('info')
spec_key_complete.append('host')
spec_key_complete.append('basePath')
spec_key_complete.append('schemes')
spec_key_complete.append('consumes')
spec_key_complete.append('produces')
spec_key_complete.append('paths')
spec_key_complete.append('definitions')
spec_key_complete.append('parameters')
spec_key_complete.append('responses')
spec_key_complete.append('securityDefinitions')
spec_key_complete.append('security')
spec_key_complete.append('tags')
spec_key_complete.append('externalDocs')

In [100]:
countkeys = ['implemented fields', 'missing fields']

In [139]:

clusterdf = onehotdf[spec_key_complete]

In [140]:
clusterdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  
1forge.com                            0     0             0  
6-dot-authentiqio.appspot.com         0     0             0  
adafruit.com                          1     0             0  
adobe.com:aem                         1     0             0  
afterbanks.com                        0     0             0

In [141]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1016 entries, 1forge.com to zuora.com
Data columns (total 2 columns):
implemented fields    1016 non-null int64
missing fields        1016 non-null int64
dtypes: int64(2)
memory usage: 23.8+ KB


# K-modes clustring
here we use k-modes clustering to cluster the apis based on their structure

In [142]:
# random categorical data
data = clusterdf

km = KModes(n_clusters=15, init='Huang', n_init=5, verbose=3)
clusters = km.fit_predict(data)
# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 118, cost: 480.0
Run 1, iteration: 2/100, moves: 11, cost: 480.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 102, cost: 589.0
Run 2, iteration: 2/100, moves: 28, cost: 587.0
Run 2, iteration: 3/100, moves: 1, cost: 587.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 96, cost: 540.0
Run 3, iteration: 2/100, moves: 8, cost: 540.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 180, cost: 484.0
Run 4, iteration: 2/100, moves: 11, cost: 484.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 135, cost: 545.0
Run 5, iteration: 2/100, moves: 1, cost: 545.0
Best run was number 1
[[1 1 1 1 1 0 1 1 1 1 0 1 1 0 0]
 [1 1 1 1 1 1 1 

In [143]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()  # for plot styling


In [144]:
len(clusters)

1016

In [145]:
cluster = list(clusters)

In [146]:
trialdf = onehotdf.copy()
trialdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [147]:
trialdf["cluster"] = cluster

In [148]:
trialdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  cluster  
1forge.com                                      7               8       13  
6-dot-authentiqio.appspot.com                   9               6        0  
adafruit.com                                   11               4        0  
adobe.com:aem                                   9               6       12  
afterbanks.com                                  8               7        4

In [149]:
def createcluster(data, num_cluster, runs=10, level=2):
    km = KModes(n_clusters=num_cluster, init='Huang', n_init=runs, verbose=level)
    clusters = km.fit_predict(data)
    print(km.cluster_centroids_)
    print(km.labels_)
    return clusters

In [150]:
cluster_dict = dict()

In [151]:
for i in range(5,13):
    cluster_run = createcluster(data, i)
    cluster_dict[i] = cluster_run

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 172, cost: 1032.0
Run 1, iteration: 2/100, moves: 7, cost: 1032.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 111, cost: 818.0
Run 2, iteration: 2/100, moves: 15, cost: 818.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 243, cost: 977.0
Run 3, iteration: 2/100, moves: 33, cost: 977.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 217, cost: 1074.0
Run 4, iteration: 2/100, moves: 44, cost: 1074.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 27, cost: 1293.0
Run 5, iteration: 2/100, moves: 14, cost: 1293.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/100, moves:

Starting iterations...
Run 2, iteration: 1/100, moves: 107, cost: 898.0
Run 2, iteration: 2/100, moves: 0, cost: 898.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 141, cost: 673.0
Run 3, iteration: 2/100, moves: 1, cost: 673.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 244, cost: 673.0
Run 4, iteration: 2/100, moves: 28, cost: 673.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 139, cost: 608.0
Run 5, iteration: 2/100, moves: 0, cost: 608.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/100, moves: 254, cost: 606.0
Run 6, iteration: 2/100, moves: 55, cost: 606.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 7, iteration: 1/100, moves: 299, cost: 972.0
Run 7, iteration: 2/100, moves: 108, cost: 916

[[1 1 1 1 1 0 0 1 1 0 0 1 0 0 0]
 [1 1 1 1 1 0 1 1 1 0 0 1 0 0 1]
 [1 1 1 1 1 0 0 1 1 1 0 1 0 1 1]
 [1 1 1 1 1 0 1 1 1 0 0 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 1 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1 1 1 0 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 0 1 1 0 1]
 [1 1 1 0 1 1 1 1 1 0 0 1 0 0 0]
 [1 1 1 0 1 1 1 1 1 1 0 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 0 0 0 1 0]
 [1 1 1 1 1 0 1 1 0 0 0 0 0 1 0]]
[11  0  3 ...  7  0 10]


In [152]:
clkeys = list(cluster_dict.keys())
clkeys

[5, 6, 7, 8, 9, 10, 11, 12]

In [153]:
for clust in cluster_dict:
    vars()["cluster"+str(clust)]=list(cluster_dict[clust])
    vars()["clusterdf"+str(clust)]=onehotdf.copy()

In [154]:
cluster5

[0,
 1,
 2,
 2,
 0,
 0,
 0,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 0,
 0,
 0,
 1,
 1,
 4,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 4,
 0,
 0,
 2,
 0,
 0,
 4,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [155]:
clusterdf5.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [157]:
clusterdf5["cluster"]=cluster5
clusterdf6["cluster"]=cluster6
clusterdf7["cluster"]=cluster7
clusterdf8["cluster"]=cluster8
clusterdf9["cluster"]=cluster9
clusterdf10["cluster"]=cluster10
clusterdf11["cluster"]=cluster11
clusterdf12["cluster"]=cluster12


In [158]:
clusterdf5.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  cluster  
1forge.com                                      7               8        0  
6-dot-authentiqio.appspot.com                   9               6        1  
adafruit.com                                   11               4        2  
adobe.com:aem                                   9               6        2  
afterbanks.com                                  8               7        0

In [159]:
with open('obj/'+ 'dfcluster_dict' + '.pkl', 'wb') as f:
        pickle.dump(cluster_dict, f, pickle.HIGHEST_PROTOCOL)

In [160]:
def saveAsPickle(name, data):
    with open('obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
    print("saved as pickle " + str(name))

In [161]:
def saveAsJson(name, data):
    savname = name + '.json'
    with open(savname, 'w') as fp:
        json.dump(data,fp)

In [162]:
clusterdf5.to_csv('cluster5.csv', encoding='utf8')

In [163]:
clusterdf6.to_csv('cluster6.csv', encoding='utf8')
clusterdf7.to_csv('cluster7.csv', encoding='utf8')
clusterdf8.to_csv('cluster8.csv', encoding='utf8')
clusterdf9.to_csv('cluster9.csv', encoding='utf8')
clusterdf10.to_csv('cluster10.csv', encoding='utf8')
clusterdf11.to_csv('cluster11.csv', encoding='utf8')
clusterdf12.to_csv('cluster12.csv', encoding='utf8')

# Text Clustering
Here we will cluster the web services based on their text

https://pythonprogramminglanguage.com/kmeans-text-clustering/

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
 
documents = descdict
 
 
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)
text = ""

true_k = 200
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=500, n_init=1)
model.fit(X)
 
print("Top terms per cluster:")
text += "Number of k %d" % true_k
text += "\n"
text += "Top terms per cluster:"
text += "\n"
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()
for i in range(true_k):
    print("Cluster %d:" % i),
    text += "Cluster %d:" % i
    text += "\n"
    for ind in order_centroids[i, :15]:
        print(' %s' % terms[ind]),
        text += ' %s' % terms[ind]
        text += "\n"
    print


In [163]:
with open("ClusterOutput200.txt", "w") as text_file:
    text_file.write(text)

In [164]:
print("\n")
print("Prediction")
 
Y = vectorizer.transform(["food"])
prediction = model.predict(Y)
print(prediction)
 
Y = vectorizer.transform(["a new  app with sql and aws"])
prediction = model.predict(Y)
print(prediction)



Prediction
[63]
[115]


In [165]:
text_testdf = onehotdf.copy()

In [166]:
labels = list(model.labels_)
print(len(labels))



1016


In [167]:
text_testdf["label"] = labels

In [168]:
text_testdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  label  
1forge.com                                      7               8     63  
6-dot-authentiqio.appspot.com                   9               6     61  
adafruit.com                                   11               4    179  
adobe.com:aem                                   9               6     87  
afterbanks.com                                  8               7     63

https://pythonprogramminglanguage.com/kmeans-elbow-method/

In [169]:
text200df = text_testdf.copy()

In [170]:
text200df.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  label  
1forge.com                                      7               8     63  
6-dot-authentiqio.appspot.com                   9               6     61  
adafruit.com                                   11               4    179  
adobe.com:aem                                   9               6     87  
afterbanks.com                                  8               7     63

In [171]:
text200df.to_csv('text200df.csv', encoding='utf8')

NameError: name 'KPrototypes' is not defined