In [1]:
import pickle
import json
import pandas
import scipy

In [2]:
descdict = dict()

with open('obj/descdict.pkl', 'rb') as handle:
    descdict = pickle.load(handle)

keys = list(descdict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [3]:
onehotdf = pandas.DataFrame()

with open('obj/onehotdf.pkl', 'rb') as handle:
    onehotdf = pickle.load(handle)

keys = list(onehotdf.keys())
print(keys)

['swagger', 'info', 'host', 'basePath', 'schemes', 'consumes', 'produces', 'paths', 'definitions', 'parameters', 'responses', 'securityDefinitions', 'security', 'tags', 'externalDocs', 'implemented fields', 'missing fields']


In [4]:
onehotdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [5]:
lemmadict = dict()

with open('obj/lemmadict.pkl', 'rb') as handle:
    lemmadict = pickle.load(handle)

keys = list(lemmadict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [6]:
onehotdict = dict()

with open('obj/onehotdict.pkl', 'rb') as handle:
    onehotdict = pickle.load(handle)

keys = list(onehotdict.keys())
print(keys)

['1forge.com', '6-dot-authentiqio.appspot.com', 'adafruit.com', 'adobe.com:aem', 'afterbanks.com', 'agco-ats.com', 'airport-web.appspot.com', 'amadeus.com', 'amazonaws.com:AWSMigrationHub', 'amazonaws.com:acm', 'amazonaws.com:alexaforbusiness', 'amazonaws.com:apigateway', 'amazonaws.com:application-autoscaling', 'amazonaws.com:appstream', 'amazonaws.com:appsync', 'amazonaws.com:athena', 'amazonaws.com:autoscaling', 'amazonaws.com:autoscaling-plans', 'amazonaws.com:batch', 'amazonaws.com:budgets', 'amazonaws.com:ce', 'amazonaws.com:cloud9', 'amazonaws.com:clouddirectory', 'amazonaws.com:cloudformation', 'amazonaws.com:cloudfront', 'amazonaws.com:cloudhsm', 'amazonaws.com:cloudhsmv2', 'amazonaws.com:cloudsearch', 'amazonaws.com:cloudsearchdomain', 'amazonaws.com:cloudtrail', 'amazonaws.com:codebuild', 'amazonaws.com:codecommit', 'amazonaws.com:codedeploy', 'amazonaws.com:codepipeline', 'amazonaws.com:codestar', 'amazonaws.com:cognito-identity', 'amazonaws.com:cognito-idp', 'amazonaws.com

In [7]:
onehotdict[keys[0]]

[1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]

In [8]:
import sys
!{sys.executable} -m pip install kmodes



You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [9]:
import numpy as np
from kmodes.kmodes import KModes


In [10]:
onehotdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [11]:
onehotdf.count

<bound method DataFrame.count of                                        swagger  info  host  basePath  schemes  \
1forge.com                                   1     1     1         1        1   
6-dot-authentiqio.appspot.com                1     1     1         1        1   
adafruit.com                                 1     1     1         1        1   
adobe.com:aem                                1     1     1         1        1   
afterbanks.com                               1     1     1         1        1   
agco-ats.com                                 1     1     1         0        1   
airport-web.appspot.com                      1     1     1         1        1   
amadeus.com                                  1     1     1         1        1   
amazonaws.com:AWSMigrationHub                1     1     1         1        1   
amazonaws.com:acm                            1     1     1         1        1   
amazonaws.com:alexaforbusiness               1     1     1         1        

# K-modes clustring
here we use k-modes clustering to cluster the apis based on their structure

In [12]:
# random categorical data
data = onehotdf

km = KModes(n_clusters=8, init='Huang', n_init=10, verbose=3)
clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 141, cost: 1353.0
Run 1, iteration: 2/100, moves: 12, cost: 1353.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 247, cost: 1288.0
Run 2, iteration: 2/100, moves: 54, cost: 1271.0
Run 2, iteration: 3/100, moves: 4, cost: 1271.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 164, cost: 1121.0
Run 3, iteration: 2/100, moves: 76, cost: 1121.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 86, cost: 1292.0
Run 4, iteration: 2/100, moves: 27, cost: 1292.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 156, cost: 1175.0
Run 5, iteration: 2/100, moves: 15, cost: 1175.0
Init: initializing centroids
Init: initializing clusters
S

In [13]:
clusters

array([7, 5, 2, ..., 4, 0, 1], dtype=uint8)

In [14]:
len(clusters)

1016

In [15]:
cluster = list(clusters)

In [16]:
trialdf = onehotdf.copy()
trialdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [17]:
trialdf["cluster"] = cluster

In [18]:
trialdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  cluster  
1forge.com                                      7               8        7  
6-dot-authentiqio.appspot.com                   9               6        5  
adafruit.com                                   11               4        2  
adobe.com:aem                                   9               6        0  
afterbanks.com                                  8               7        7

In [19]:
def createcluster(data, num_cluster, runs=10, level=2):
    km = KModes(n_clusters=num_cluster, init='Huang', n_init=runs, verbose=level)
    clusters = km.fit_predict(data)
    print(km.cluster_centroids_)
    return clusters

In [20]:
cluster_dict = dict()

In [21]:
for i in range(5,13):
    cluster_run = createcluster(data, i)
    cluster_dict[i] = cluster_run

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 251, cost: 1535.0
Run 1, iteration: 2/100, moves: 14, cost: 1535.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 222, cost: 1944.0
Run 2, iteration: 2/100, moves: 51, cost: 1944.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 145, cost: 1594.0
Run 3, iteration: 2/100, moves: 0, cost: 1594.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 114, cost: 1718.0
Run 4, iteration: 2/100, moves: 59, cost: 1718.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 70, cost: 2204.0
Run 5, iteration: 2/100, moves: 29, cost: 2176.0
Run 5, iteration: 3/100, moves: 5, cost: 2176.0
Init: initializing centroids
Init: initializing clusters
St

Run 8, iteration: 1/100, moves: 209, cost: 1314.0
Run 8, iteration: 2/100, moves: 37, cost: 1306.0
Run 8, iteration: 3/100, moves: 1, cost: 1306.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 9, iteration: 1/100, moves: 265, cost: 1194.0
Run 9, iteration: 2/100, moves: 91, cost: 1136.0
Run 9, iteration: 3/100, moves: 108, cost: 1136.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 10, iteration: 1/100, moves: 164, cost: 1140.0
Run 10, iteration: 2/100, moves: 64, cost: 1077.0
Run 10, iteration: 3/100, moves: 26, cost: 1077.0
Best run was number 10
[[ 1  1  1  1  1  1  1  1  1  0  0  0  0  1  0 10  5]
 [ 1  1  1  1  1  0  0  1  1  1  0  1  0  1  1 11  4]
 [ 1  1  1  0  1  1  1  1  1  1  0  1  1  0  0 11  4]
 [ 1  1  1  1  1  0  1  1  1  0  0  1  1  0  0 10  5]
 [ 1  1  1  0  1  1  1  1  1  1  0  1  0  0  0 10  5]
 [ 1  1  1  1  1  0  1  1  1  0  0  0  0  0  0  8  7]
 [ 1  1  1  1  1  1  1  1  1  1  0  1  1  0  1

Run 1, iteration: 1/100, moves: 209, cost: 1482.0
Run 1, iteration: 2/100, moves: 2, cost: 1482.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 212, cost: 1000.0
Run 2, iteration: 2/100, moves: 17, cost: 1000.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 126, cost: 986.0
Run 3, iteration: 2/100, moves: 0, cost: 986.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 97, cost: 907.0
Run 4, iteration: 2/100, moves: 29, cost: 895.0
Run 4, iteration: 3/100, moves: 1, cost: 895.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 193, cost: 994.0
Run 5, iteration: 2/100, moves: 60, cost: 961.0
Run 5, iteration: 3/100, moves: 3, cost: 961.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/

In [22]:
clkeys = list(cluster_dict.keys())
clkeys

[5, 6, 7, 8, 9, 10, 11, 12]

In [25]:
for clust in cluster_dict:
    vars()["cluster"+str(clust)]=list(cluster_dict[clust])
    vars()["clusterdf"+str(clust)]=onehotdf.copy()

In [26]:
cluster5

[0,
 0,
 3,
 0,
 0,
 0,
 1,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 0,
 1,
 2,
 0,
 3,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 4,
 0,
 0,
 3,
 0,
 0,
 4,
 0,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [27]:
clusterdf5.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  
1forge.com                                      7               8  
6-dot-authentiqio.appspot.com                   9               6  
adafruit.com                                   11               4  
adobe.com:aem                                   9               6  
afterbanks.com                                  8               7

In [28]:
clusterdf5["cluster"]=cluster5
clusterdf6["cluster"]=cluster6
clusterdf7["cluster"]=cluster7
clusterdf8["cluster"]=cluster8
clusterdf9["cluster"]=cluster9
clusterdf10["cluster"]=cluster10
clusterdf11["cluster"]=cluster11
clusterdf12["cluster"]=cluster12


In [29]:
clusterdf5.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  cluster  
1forge.com                                      7               8        0  
6-dot-authentiqio.appspot.com                   9               6        0  
adafruit.com                                   11               4        3  
adobe.com:aem                                   9               6        0  
afterbanks.com                                  8               7        0

In [30]:
with open('obj/'+ 'cluster_dict' + '.pkl', 'wb') as f:
        pickle.dump(cluster_dict, f, pickle.HIGHEST_PROTOCOL)

In [31]:
def saveAsPickle(name, data):
    with open('obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
    print("saved as pickle " + str(name))

In [32]:
def saveAsJson(name, data):
    savname = name + '.json'
    with open(savname, 'w') as fp:
        json.dump(data,fp)

In [33]:
clusterdf5.to_csv('cluster5.csv', encoding='utf8')

In [34]:
#clusterdf6.to_csv('cluster6.csv', encoding='utf8')
#clusterdf7.to_csv('cluster7.csv', encoding='utf8')
#clusterdf8.to_csv('cluster8.csv', encoding='utf8')
#clusterdf9.to_csv('cluster9.csv', encoding='utf8')
#clusterdf10.to_csv('cluster10.csv', encoding='utf8')
#clusterdf11.to_csv('cluster11.csv', encoding='utf8')
#clusterdf12.to_csv('cluster12.csv', encoding='utf8')

# Text Clustering
Here we will cluster the web services based on their text

https://pythonprogramminglanguage.com/kmeans-text-clustering/

In [162]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
 
documents = descdict
 
 
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)
text = ""

true_k = 200
model = KMeans(n_clusters=true_k, init='k-means++', max_iter=500, n_init=1)
model.fit(X)
 
print("Top terms per cluster:")
text += "Number of k %d" % true_k
text += "\n"
text += "Top terms per cluster:"
text += "\n"
order_centroids = model.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()
for i in range(true_k):
    print("Cluster %d:" % i),
    text += "Cluster %d:" % i
    text += "\n"
    for ind in order_centroids[i, :15]:
        print(' %s' % terms[ind]),
        text += ' %s' % terms[ind]
        text += "\n"
    print


Top terms per cluster:
Cluster 0:
 androidmanagement
 googleapis
 com
 zuora
 edgegatewaypool
 edu
 eff
 elasticache
 elasticbeanstalk
 elasticfilesystem
 ecs
 elasticloadbalancing
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
Cluster 1:
 luis
 cognitiveservices
 programmatic
 runtime
 azure
 com
 elasticbeanstalk
 edu
 eff
 elasticache
 elasticloadbalancing
 elasticfilesystem
 edgegateway
 elasticloadbalancingv2
 elasticmapreduce
Cluster 2:
 entitlement
 marketplace
 amazonaws
 com
 elasticfilesystem
 edgegatewaypool
 edu
 eff
 elasticache
 elasticbeanstalk
 elasticloadbalancing
 encryptionprotectors
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
Cluster 3:
 datamasking
 sql
 azure
 com
 elasticbeanstalk
 edgegatewaypool
 edu
 eff
 elasticache
 zuora
 edgegateway
 elasticloadbalancing
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
Cluster 4:
 volume
 azsadmin
 azure
 com
 elasticbeanstalk
 edgegatewaypool
 edu
 eff
 elasticache
 zuora
 edgegateway
 elasticl

 elasticbeanstalk
 elasticloadbalancing
 endpointservice
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
 elastictranscoder
Cluster 142:
 mturk
 requester
 amazonaws
 com
 elasticbeanstalk
 edgegateway
 edgegatewaypool
 edu
 eff
 elasticache
 zuora
 ecs
 elasticloadbalancing
 elasticloadbalancingv2
 elasticmapreduce
Cluster 143:
 certification
 hetras
 net
 booking
 hotel
 eff
 ecs
 edgegateway
 edgegatewaypool
 edu
 zuora
 elasticache
 ecr
 elasticfilesystem
 elasticloadbalancing
Cluster 144:
 gesamtausgabe
 weber
 elasticfilesystem
 edgegateway
 edgegatewaypool
 edu
 eff
 elasticache
 elasticbeanstalk
 elasticloadbalancing
 doubleclicksearch
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
 elastictranscoder
Cluster 145:
 machinelearningcompute
 azure
 com
 zuora
 elasticfilesystem
 edgegatewaypool
 edu
 eff
 elasticache
 elasticbeanstalk
 elasticloadbalancing
 endpointservice
 elasticloadbalancingv2
 elasticmapreduce
 elasticpools
Cluster 146:
 flickr
 com
 elasticbea

In [163]:
with open("ClusterOutput200.txt", "w") as text_file:
    text_file.write(text)

In [164]:
print("\n")
print("Prediction")
 
Y = vectorizer.transform(["food"])
prediction = model.predict(Y)
print(prediction)
 
Y = vectorizer.transform(["a new  app with sql and aws"])
prediction = model.predict(Y)
print(prediction)



Prediction
[63]
[115]


In [165]:
text_testdf = onehotdf.copy()

In [166]:
labels = list(model.labels_)
print(len(labels))



1016


In [167]:
text_testdf["label"] = labels

In [168]:
text_testdf.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  label  
1forge.com                                      7               8     63  
6-dot-authentiqio.appspot.com                   9               6     61  
adafruit.com                                   11               4    179  
adobe.com:aem                                   9               6     87  
afterbanks.com                                  8               7     63

https://pythonprogramminglanguage.com/kmeans-elbow-method/

In [169]:
text200df = text_testdf.copy()

In [170]:
text200df.head()

swagger  info  host  basePath  schemes  \
1forge.com                           1     1     1         1        1   
6-dot-authentiqio.appspot.com        1     1     1         1        1   
adafruit.com                         1     1     1         1        1   
adobe.com:aem                        1     1     1         1        1   
afterbanks.com                       1     1     1         1        1   

                               consumes  produces  paths  definitions  \
1forge.com                            0         1      1            0   
6-dot-authentiqio.appspot.com         0         0      1            1   
adafruit.com                          0         1      1            1   
adobe.com:aem                         0         0      1            1   
afterbanks.com                        0         1      1            1   

                               parameters  responses  securityDefinitions  \
1forge.com                              0          0                    0   
6-dot-authentiqio.appspot.com           1          1                    0   
adafruit.com                            1          0                    1   
adobe.com:aem                           0          0                    1   
afterbanks.com                          0          0                    0   

                               security  tags  externalDocs  \
1forge.com                            0     0             0   
6-dot-authentiqio.appspot.com         0     0             0   
adafruit.com                          1     0             0   
adobe.com:aem                         1     0             0   
afterbanks.com                        0     0             0   

                               implemented fields  missing fields  label  
1forge.com                                      7               8     63  
6-dot-authentiqio.appspot.com                   9               6     61  
adafruit.com                                   11               4    179  
adobe.com:aem                                   9               6     87  
afterbanks.com                                  8               7     63

In [171]:
text200df.to_csv('text200df.csv', encoding='utf8')